"""Add DealerInventory model"""

revision = "1697652c68bf"
down_revision = "20260731_0009"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dealer_inventories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dealer_id", sa.Integer(), nullable=False),
        sa.Column("pickup_request_id", sa.Integer(), nullable=False),
        sa.Column("material_type", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("quantity_kg", sa.Float(), nullable=False),
        sa.Column("price_per_kg", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("total_value", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("quality_grade", sa.String(length=30), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "available", "reserved", "sold", name="dealerinventorystatus", native_enum=False
            ),
            server_default="available",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("price_per_kg >= 0", name="ck_dealer_inventories_price_non_negative"),
        sa.CheckConstraint("quantity_kg > 0", name="ck_dealer_inventories_quantity_positive"),
        sa.CheckConstraint(
            "total_value >= 0", name="ck_dealer_inventories_total_value_non_negative"
        ),
        sa.ForeignKeyConstraint(["dealer_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["pickup_request_id"], ["pickup_requests.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dealer_inventories_category"), "dealer_inventories", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_dealer_inventories_created_at"), "dealer_inventories", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_dealer_inventories_dealer_id"), "dealer_inventories", ["dealer_id"], unique=False
    )
    op.create_index(op.f("ix_dealer_inventories_id"), "dealer_inventories", ["id"], unique=False)
    op.create_index(
        op.f("ix_dealer_inventories_pickup_request_id"),
        "dealer_inventories",
        ["pickup_request_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_dealer_inventories_status"), "dealer_inventories", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_dealer_inventories_status"), table_name="dealer_inventories")
    op.drop_index(op.f("ix_dealer_inventories_pickup_request_id"), table_name="dealer_inventories")
    op.drop_index(op.f("ix_dealer_inventories_id"), table_name="dealer_inventories")
    op.drop_index(op.f("ix_dealer_inventories_dealer_id"), table_name="dealer_inventories")
    op.drop_index(op.f("ix_dealer_inventories_created_at"), table_name="dealer_inventories")
    op.drop_index(op.f("ix_dealer_inventories_category"), table_name="dealer_inventories")
    op.drop_table("dealer_inventories")
    # ### end Alembic commands ###
